# Generated by Django 5.2.17 on 2026-09-15 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('referentials', '0002_alter_departement_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membre',
            field=models.OneToOneField(blank=True, help_text='Obligatoire pour les maitres de stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='referentials.membre'),
        ),
    ]
