# Generated by Django 5.2.17 on 2026-10-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_rename_membre_personnel'),
        ('referentiels', '0003_data_permissions_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='personnel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compte', to='referentiels.personnel', verbose_name='personnel associé'),
        ),
    ]
