# Generated by Django 5.2.17 on 2026-10-03 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comptes', '0003_alter_utilisateur_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('est_systeme', models.BooleanField(default=False, verbose_name='rôle système')),
                ('groupe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='auth.group', verbose_name='groupe')),
            ],
            options={
                'verbose_name': 'Profil de rôle',
                'verbose_name_plural': 'Profils de rôle',
                'ordering': ['-est_systeme', 'groupe__name'],
            },
        ),
    ]
