# Generated by Django 5.2.17 on 2026-10-02 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0004_typestage_durees'),
        ('stages', '0003_fix_fk_maitre_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationMaitreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateTimeField(auto_now_add=True, verbose_name="date d'affectation")),
                ('affecte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='affecté par')),
                ('maitre_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='referentiels.personnel', verbose_name='maître de stage')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_maitre', to='stages.stage', verbose_name='stage')),
            ],
            options={
                'verbose_name': 'Affectation de maître de stage',
                'verbose_name_plural': 'Affectations de maître de stage',
                'ordering': ['-date_affectation'],
            },
        ),
    ]
