# Generated by Django 5.2.17 on 2026-10-03 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_lot_d'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeInterruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name="date d'interruption")),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de reprise')),
                ('motif_interruption', models.TextField(verbose_name="motif d'interruption")),
                ('motif_reprise', models.TextField(blank=True, verbose_name='motif de reprise')),
                ('interrompu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='interrompu par')),
                ('repris_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='repris par')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_interruption', to='stages.stage', verbose_name='stage')),
            ],
            options={
                'verbose_name': "Période d'interruption",
                'verbose_name_plural': "Périodes d'interruption",
                'ordering': ['date_debut', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='periode_interruption_reprise_apres_interruption'), models.UniqueConstraint(condition=models.Q(('date_fin__isnull', True)), fields=('stage',), name='periode_interruption_une_seule_ouverte_par_stage')],
            },
        ),
    ]
