# Generated by Django 5.2.17 on 2026-10-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_periodes_stages_deja_interrompus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['-date_debut'], 'permissions': [('consulter_vivier', 'Consulter le vivier de talents'), ('exporter_vivier', 'Exporter le vivier (CSV)'), ('telecharger_rapports', 'Télécharger les rapports de stage')], 'verbose_name': 'Stage', 'verbose_name_plural': 'Stages'},
        ),
    ]
