# Generated by Django 5.2.17 on 2026-10-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0007_permissions_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='alerte_demarrage_envoyee',
            field=models.BooleanField(default=False, verbose_name='alerte « à démarrer » envoyée'),
        ),
        migrations.AddField(
            model_name='stage',
            name='alerte_fin_envoyee',
            field=models.BooleanField(default=False, verbose_name='alerte « à terminer » envoyée'),
        ),
    ]
