# Generated by Django 5.2.17 on 2026-09-15 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalDiffusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('LINKEDIN', 'LinkedIn'), ('SITE_WEB', 'Site web'), ('AUTRE', 'Autre')], max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('compte', models.CharField(blank=True, help_text='Nom du compte ou de la page', max_length=150)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canal de diffusion',
                'verbose_name_plural': 'Canaux de diffusion',
                'ordering': ['type', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Burkina Faso', max_length=100)),
                ('type', models.CharField(choices=[('LYCEE', 'Lycée'), ('UNIVERSITE', 'Université'), ('ECOLE_PRO', 'École professionnelle'), ('AUTRE', 'Autre')], max_length=20)),
                ('partenaire', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('duree_min_mois', models.PositiveIntegerField(help_text='Durée minimale en mois')),
                ('duree_max_mois', models.PositiveIntegerField(help_text='Durée maximale en mois')),
                ('remunere', models.BooleanField(default=False, help_text='Stage rémunéré ?')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de stage',
                'verbose_name_plural': 'Types de stage',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membres', to='referentials.departement')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'prenom'],
                'unique_together': {('nom', 'prenom', 'departement')},
            },
        ),
    ]
