# Generated by Django 5.2.17 on 2026-09-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
