# Generated by Django 5.2.17 on 2026-09-15 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Le responsable doit être un membre de ce département.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to='referentials.membre'),
        ),
    ]
