# Generated by Django 5.2.17 on 2026-09-25 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('lien', models.CharField(blank=True, max_length=200, verbose_name='lien')),
                ('lue', models.BooleanField(default=False, verbose_name='lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='identifiant objet')),
                ('ancien_statut', models.CharField(blank=True, max_length=30, verbose_name='ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, max_length=30, verbose_name='nouveau statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="date de l'action")),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="type d'objet")),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='suivi_histo_content_b61b04_idx')],
            },
        ),
    ]
