# Generated by Django 5.2.17 on 2026-09-25 20:51

import candidatures.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offres', '0001_initial'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('telephone', models.CharField(db_index=True, max_length=20, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('niveau_etudes', models.CharField(blank=True, max_length=100, verbose_name="niveau d'études")),
                ('filiere', models.CharField(blank=True, max_length=150, verbose_name='filière')),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidats', to='referentiels.etablissement', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='référence')),
                ('type_demande', models.CharField(choices=[('SPONTANEE', 'Spontanée'), ('SUITE_OFFRE', 'Suite à une offre')], max_length=20, verbose_name='type de demande')),
                ('debut_disponibilite', models.DateField(verbose_name='début de disponibilité')),
                ('fin_disponibilite', models.DateField(verbose_name='fin de disponibilité')),
                ('duree_souhaitee', models.PositiveSmallIntegerField(verbose_name='durée souhaitée (semaines)')),
                ('statut', models.CharField(choices=[('RECUE', 'Reçue'), ('EN_TRAITEMENT', 'En traitement'), ('ACCORDEE', 'Accordée'), ('REFUSEE', 'Refusée')], default='RECUE', max_length=20, verbose_name='statut')),
                ('motif_refus', models.CharField(blank=True, choices=[('PROFIL_INADAPTE', 'Profil inadapté'), ('PERIODE_INDISPONIBLE', 'Période indisponible'), ('QUOTA_ATTEINT', 'Quota atteint'), ('DESISTEMENT', 'Désistement'), ('AUTRE', 'Autre')], max_length=30, verbose_name='motif de refus')),
                ('precision_motif', models.TextField(blank=True, verbose_name='précision du motif')),
                ('date_entretien', models.DateTimeField(blank=True, null=True, verbose_name="date d'entretien")),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('candidat_informe', models.BooleanField(default=False, verbose_name='candidat informé')),
                ('date_information', models.DateTimeField(blank=True, null=True, verbose_name="date d'information")),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='date de dépôt')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='candidatures.candidat', verbose_name='candidat')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='referentiels.departement', verbose_name='département')),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='offres.offre', verbose_name='offre')),
                ('type_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='referentiels.typestage', verbose_name='type de stage')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('CV', 'CV'), ('LETTRE_MOTIVATION', 'Lettre de motivation'), ('LETTRE_DEMANDE', 'Lettre de demande'), ('LETTRE_RECOMMANDATION', 'Lettre de recommandation'), ('AUTRE', 'Autre')], max_length=30, verbose_name='type de pièce')),
                ('fichier', models.FileField(upload_to='candidatures/%Y/%m/', validators=[candidatures.models._valider_piece_jointe], verbose_name='fichier')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='candidatures.candidature', verbose_name='candidature')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['type_piece'],
            },
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['RECUE', 'EN_TRAITEMENT'])), fields=('candidat',), name='candidature_unique_active_par_candidat'),
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('offre__isnull', False), ('type_demande', 'SUITE_OFFRE')), models.Q(('offre__isnull', True), ('type_demande', 'SPONTANEE')), _connector='OR'), name='candidature_offre_coherente_type_demande'),
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.CheckConstraint(condition=models.Q(('fin_disponibilite__gt', models.F('debut_disponibilite'))), name='candidature_fin_dispo_gt_debut'),
        ),
    ]
