# Generated by Django 5.2.17 on 2026-09-26 04:00

import candidatures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecejointe',
            name='nom_original',
            field=models.CharField(blank=True, max_length=255, verbose_name='nom original'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='telephone',
            field=models.CharField(max_length=20, unique=True, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='duree_souhaitee',
            field=models.PositiveSmallIntegerField(help_text='Durée en mois entiers.', verbose_name='durée souhaitée (mois)'),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='fichier',
            field=models.FileField(storage=candidatures.models._get_stockage_prive, upload_to=candidatures.models._piece_upload_path, validators=[candidatures.models._valider_piece_jointe], verbose_name='fichier'),
        ),
    ]
