# Generated by Django 5.2.17 on 2026-09-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0003_alter_candidat_niveau_etudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='etablissement_autre',
            field=models.CharField(blank=True, help_text="Remplir uniquement si l'établissement n'est pas dans la liste.", max_length=200, verbose_name='établissement (saisie libre)'),
        ),
    ]
