# Generated by Django 5.2.17 on 2026-09-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0004_candidat_etablissement_autre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='niveau_etudes',
            field=models.CharField(blank=True, choices=[('BAC', 'Bac'), ('BTS', 'BTS / DUT'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('DOC', 'Doctorat'), ('AUTRE', 'Autre')], max_length=10, verbose_name="niveau d'études"),
        ),
    ]
