# Generated by Django 5.2.17 on 2026-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0006_rg09_autre_et_unicite_pieces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='type_demande',
            field=models.CharField(choices=[('SPONTANEE', 'Spontanée'), ('SUITE_OFFRE', 'Suite à une offre'), ('AUTRE', 'Autre')], max_length=20, verbose_name='type de demande'),
        ),
    ]
