# Generated by Django 5.2.17 on 2026-10-02 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0007_alter_candidature_type_demande'),
        ('referentiels', '0004_typestage_durees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='alerte_entretien_envoyee',
            field=models.BooleanField(default=False, verbose_name='alerte entretien envoyée'),
        ),
        migrations.CreateModel(
            name='TransfertCandidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='motif')),
                ('date_transfert', models.DateTimeField(auto_now_add=True, verbose_name='date de transfert')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='candidatures.candidature', verbose_name='candidature')),
                ('departement_cible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='referentiels.departement', verbose_name='département cible')),
                ('departement_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='referentiels.departement', verbose_name='département source')),
                ('realise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='réalisé par')),
            ],
            options={
                'verbose_name': 'Transfert de candidature',
                'verbose_name_plural': 'Transferts de candidature',
                'ordering': ['-date_transfert'],
            },
        ),
    ]
