# Generated by Django 5.2.17 on 2026-10-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0008_lot_d'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piecejointe',
            options={'ordering': ['type_piece'], 'permissions': [('telecharger_pieces_jointes', 'Télécharger les pièces jointes des candidats')], 'verbose_name': 'Pièce jointe', 'verbose_name_plural': 'Pièces jointes'},
        ),
    ]
