# Generated by Django 5.2.17 on 2026-10-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0009_permission_pieces_jointes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='alerte_disponibilite_envoyee',
            field=models.BooleanField(default=False, verbose_name='alerte disponibilité envoyée'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='alerte_disponibilite_stage_envoyee',
            field=models.BooleanField(default=False, verbose_name='alerte disponibilité sans stage envoyée'),
        ),
    ]
