# Generated by Django 5.2.17 on 2026-09-25 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('profil_recherche', models.TextField(verbose_name='profil recherché')),
                ('nombre_places', models.PositiveSmallIntegerField(verbose_name='nombre de places')),
                ('statut', models.CharField(choices=[('ENVOYE', 'Envoyé'), ('PRIS_EN_CHARGE', 'Pris en charge'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], default='ENVOYE', max_length=20, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='besoins', to='referentiels.departement', verbose_name='département')),
                ('type_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='besoins', to='referentiels.typestage', verbose_name='type de stage')),
            ],
            options={
                'verbose_name': 'Besoin',
                'verbose_name_plural': 'Besoins',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('profil_recherche', models.TextField(verbose_name='profil recherché')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('nombre_places', models.PositiveSmallIntegerField(verbose_name='nombre de places')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('OUVERTE', 'Ouverte'), ('SUSPENDUE', 'Suspendue'), ('FERMEE', 'Fermée')], default='BROUILLON', max_length=20, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('besoin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offre', to='offres.besoin', verbose_name='besoin associé')),
                ('type_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='referentiels.typestage', verbose_name='type de stage')),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_publication', models.DateField(verbose_name='date de publication')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='referentiels.canalpublication', verbose_name='canal')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='offres.offre', verbose_name='offre')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.AddConstraint(
            model_name='besoin',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_places__gte', 1)), name='besoin_nombre_places_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='besoin',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='besoin_date_fin_gt_date_debut'),
        ),
        migrations.AddConstraint(
            model_name='offre',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_places__gte', 1)), name='offre_nombre_places_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='offre',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='offre_date_fin_gt_date_debut'),
        ),
    ]
