# Generated by Django 5.2.17 on 2026-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0002_parametre_offre_departement_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='texte_publie',
            field=models.TextField(blank=True, help_text='Texte généré à la création depuis le modèle. Modifiable par la secrétaire.', verbose_name="texte de l'offre"),
        ),
        migrations.AlterField(
            model_name='parametreoffre',
            name='contact',
            field=models.TextField(blank=True, help_text="Coordonnées de contact affichées dans le texte de l'offre.", verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='parametreoffre',
            name='texte_modele',
            field=models.TextField(blank=True, help_text='Variables disponibles : {contact}, {type_stage}, {departement}, {duree_min}, {duree_max}, {nombre_places}, {date_debut}, {date_fin}.', verbose_name='modèle de texte'),
        ),
    ]
